baseURL = "https://www.aaronhelton.com/"
languageCode = "en-us"
title = "Aaron Helton"
theme = "introduction"

[params]
    themeStyle = "light"
    author = "Aaron Helton"
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "abhelton@gmail.com"
    customCSS                    = ["style.css"]

    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "America/New_York"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"                # https://momentjs.com/docs/#/displaying/format/


    [params.share]
        twitter                  = true
        facebook                 = true
    
    [[params.social]]
        url   = "https://twitter.com/MariusAgricola"
        icon  = "twitter" 
        icon_pack = "fab"

    [[params.social]]
        url = "mailto:abhelton@gmail.com"  
        icon = "paper-plane" 
        icon_pack = "fas"

    [[params.social]]
        url = "https://github.com/aaronhelton"
        icon = "github"
        icon_pack = "fab"

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            footnote = true
        [markup.goldmark.renderer]
            unsafe = true